import Header from '../components/Header.jsx'
import Footer from '../components/Footer.jsx'

export const metadata = {
  title: "Layouts",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      <Footer />
      </body>
    </html>
  );
}
