import { Suspense } from "react"
import loading from './loading.js'

export const metadata = {
  title: 'Routing',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}>
          <Suspense fallback={<loading />}>{children}</Suspense>
        </body>

    </html>
  )
}
